### ISSUE TITLE
Compatibility with react vite

### ISSUE THREAD

**Issue by liningpan** [lifeiscontent/storybook-addon-apollo-client#102]
I can't seem to get this plugin working with React Vite. It seems link the addon is not loading at all. Although I'm using pnpm (w/o hoist) and Bazel, other plugins work fine. I'm not quite sure where the problem is.

**Comment by MIreland** [comment]
I'm seeing a similar issue.

The exact error text I am seeing:
```
file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:43799
    const err = new Error('The server is being restarted or closed. Request is outdated');
                ^

Error: The server is being restarted or closed. Request is outdated
    at throwClosedServerError (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:43799:17)
    at transformRequest (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:54782:9)
    at Object.transformRequest (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:64995:20)
    at preTransformRequest (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:64631:12)
    at processNodeUrl (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:64458:13)
    at file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:64540:17
    at traverseNodes (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37401:5)
    at file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:48
    at Array.forEach (<anonymous>)
    at traverseNodes (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:25)
    at file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:48
    at Array.forEach (<anonymous>)
    at traverseNodes (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:25)
    at file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:48
    at Array.forEach (<anonymous>)
    at traverseNodes (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37405:25)
    at traverseHtml (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:37418:5)
    at async devHtmlHook (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:64532:5)
    at async applyHtmlTransforms (file:///Users/user/Desktop/orthlyweb/node_modules/.pnpm/vite@4.4.9_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-df561101.js:38015:21)
    at async /Users/user/Desktop/orthlyweb/node_modules/.pnpm/@storybook+builder-vite@7.2.0_typescript@5.0.4_vite@4.4.9/node_modules/@storybook/builder-vite/dist/index.js:159:12246 {
  code: 'ERR_CLOSED_SERVER'
}
```

Then storybook shuts down.

**Comment by liningpan** [comment]
I'm seeing a different mode of failure. In my case, the server will run normally, only it won't load this specific plugin.

**Comment by yashwanth1796** [comment]
I am also seeing an issue but it's somewhat different

`SyntaxError: The requested module '/@fs/Users/ykumar/Desktop/GIT/foundations/node_modules/@babel/runtime/helpers/taggedTemplateLiteralLoose.js?v=223477d7' does not provide an export named 'default' (at TestQuery.ts:1:8)
error @ runtime.js:4`

![Uploading Screenshot 2024-01-11 at 10.31.17 AM.png…]()

**Comment by lifeiscontent** [comment]
@yashwanth1796 @liningpan @MIreland should be fixed now
