### ISSUE TITLE
NullInjectorError: No provider for Apollo!

### ISSUE THREAD

**Issue by alanhobbart** [lifeiscontent/storybook-addon-apollo-client#87]
I'm using apollo-angular and storybook, latest versions.
When i try to load a story with the apolloClient parameters I get NullInjectorError: No provider for Apollo!

Has anyone used storybook-addon-apollo-client wih angular? It worked fine in a react app for me.

Full error
applyDecorators was not supported :( !
core.mjs:8506 ERROR NullInjectorError: R3InjectorError(StorybookModule)[Apollo -> Apollo -> Apollo]: 
  NullInjectorError: No provider for Apollo!
    at NullInjector.get (core.mjs:7599:1)
    at R3Injector.get (core.mjs:8020:1)
    at R3Injector.get (core.mjs:8020:1)
    at R3Injector.get (core.mjs:8020:1)
    at ChainedInjector.get (core.mjs:12179:1)
    at lookupTokenUsingModuleInjector (core.mjs:3255:1)
    at getOrCreateInjectable (core.mjs:3300:1)
    at ɵɵdirectiveInject (core.mjs:10135:1)
    at NodeInjectorFactory.IntroComponent_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at getNodeInjectable (core.mjs:3485:1)

**Comment by lifeiscontent** [comment]
@alanhobbart if you want to add support, happy to add it, currently only works with react but the 7.0 release of storybook is supposed to make these kinds of multi-framework integrations easier, so if you can't maybe I'll look into adding it soon.

**Comment by lifeiscontent** [comment]
now in v10, you can do whatever you want, the addon only asks for the state it needs.
