### ISSUE TITLE
error with upgrade to 5.0.0

### ISSUE THREAD

**Issue by erwan-joly** [lifeiscontent/storybook-addon-apollo-client#98]
after upgrading to 5.0.0 from 4.1.4 i'm getting the error on some of the stories. How can I fix that ?

Cannot read properties of undefined (reading 'request')
TypeError: Cannot read properties of undefined (reading 'request')
    at https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/7555.ce656997.iframe.bundle.js:2:1059913
    at Array.map (<anonymous>)
    at Object.create (https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/7555.ce656997.iframe.bundle.js:2:1059877)
    at https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/sb-preview/runtime.js:7:16317
    at Array.forEach (<anonymous>)
    at HooksContext.triggerEffects (https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/sb-preview/runtime.js:7:16242)
    at HooksContext.renderListener (https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/sb-preview/runtime.js:7:15496)
    at https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/sb-preview/runtime.js:4:92863
    at Array.forEach (<anonymous>)
    at Channel.handleEvent (https://62f991331fc0ac4fa2bc1e46-opgjapcncc.chromatic.com/sb-preview/runtime.js:4:92847)

**Comment by lifeiscontent** [comment]
@erwan-joly sorry this isn't a helpful report, I'm happy to support you however I can, but I need something actionable in order to make reasonable fixes.

**Comment by erwan-joly** [comment]
@lifeiscontent I finally found the reason. This is happening when in the list of requests you have an empty spot (i had a typo on coma)

{
            request: {},
            result: {}
 }, , {
            request: {},
            result: {}
 }
 
 used to work but now seems to fails. It works well if you remove the double coma
